import Foundation
import StorybirdCore
import StorybirdMCPKit
@testable import Storybird
import XCTest

@MainActor
final class LegacyVideoContractTests: XCTestCase {
    private let projectID = UUID(uuidString: "11111111-1111-1111-1111-111111111111")!

    // Generated with the actual Models.swift + VideoTimelineSchedule.swift at
    // 398e96b, using only synthetic values, then whitespace-compacted here.
    // This is supported historical Cue video, before scene/audio-layer fields.
    // The earliest committed video model (d4ab407) already has all three Cue
    // components; its parent (dbd60d0) has screenshot projects only. No committed
    // pre-Cue video schema or schemaVersion gate was found. Do not mislabel the
    // deliberately damaged fixture below as an actual released legacy format.
    private var historicalLibrary: Data {
        Data(#"""
        [{
          "id":"11111111-1111-1111-1111-111111111111","revision":7,
          "name":"Synthetic historical video","summary":"History fixture; no captured content",
          "createdAt":"1970-01-01T00:00:00Z","updatedAt":"1970-01-01T00:01:00Z",
          "recording":{"filename":"recording.mp4","duration":4,"width":320,"height":180},
          "clips":[{"id":"22222222-2222-2222-2222-222222222222","kind":"video",
            "sourceStart":0,"sourceEnd":4,"playbackRate":1,"freezeDuration":0}],
          "clicks":[{
            "id":"33333333-3333-3333-3333-333333333333","button":"left",
            "sourceTime":1,"time":1,"x":0.25,"y":0.75,
            "indicator":{"startTime":0.85,"endTime":2.85,"colorHex":"#5B5CE2","size":1,"opacity":1},
            "description":{"startTime":0.85,"endTime":2.85,"position":"automatic",
              "x":0.5,"y":0.5,"text":"Synthetic click",
              "style":{"backgroundHex":"#11131A","backgroundOpacity":0.72,
                "fontSize":17,"foregroundHex":"#FFFFFF"}},
            "cueSubtitle":{"startTime":0.85,"endTime":2.85,"position":"bottom",
              "text":"Synthetic subtitle","style":{"backgroundHex":"#11131A",
                "backgroundOpacity":0.72,"fontSize":17,"foregroundHex":"#FFFFFF"}}
          }],
          "narrations":[{"id":"44444444-4444-4444-4444-444444444444",
            "voiceProfileID":"55555555-5555-5555-5555-555555555555",
            "filename":"narration.wav","text":"Synthetic narration","language":"english",
            "startTime":0.5,"duration":1.25,"volume":0.375}],
          "effects":[],"events":[],"steps":[],"subtitles":[],"suggestions":[],
          "theme":{"accentHex":"#5B5CE2","backgroundHex":"#11131A","showsBranding":true}
        }]
        """#.utf8)
    }

    // Generated by the actual dbd60d0 Models.swift encoder. This is the
    // unsupported historical model: screenshots and branching hotspots, with
    // no recording, timeline, Cue or revision fields.
    private var historicalScreenshotLibrary: Data {
        Data(#"""
        [{
          "id":"11111111-1111-1111-1111-111111111111",
          "name":"Synthetic historical screenshot project",
          "summary":"Real dbd60d0 shape; no captured content",
          "createdAt":"1970-01-01T00:00:00Z","updatedAt":"1970-01-01T00:01:00Z",
          "steps":[{
            "id":"66666666-6666-6666-6666-666666666666","title":"First",
            "caption":"Original step caption","assetFilename":"first.png",
            "subtitlePosition":"bottom",
            "subtitleStyle":{"backgroundHex":"#11131A","backgroundOpacity":0.72},
            "hotspots":[{
              "id":"88888888-8888-8888-8888-888888888888","kind":"click",
              "title":"Continue","body":"Synthetic target","caption":"Original hotspot caption",
              "x":0.25,"y":0.75,"targetStepID":"77777777-7777-7777-7777-777777777777",
              "captionStyle":{"backgroundHex":"#11131A","backgroundOpacity":0.72}
            }]
          },{
            "id":"77777777-7777-7777-7777-777777777777","title":"Second",
            "caption":"","assetFilename":"second.png","subtitlePosition":"bottom",
            "subtitleStyle":{"backgroundHex":"#11131A","backgroundOpacity":0.72},"hotspots":[]
          }],
          "events":[],
          "theme":{"accentHex":"#5B5CE2","backgroundHex":"#11131A","showsBranding":true}
        }]
        """#.utf8)
    }

    private func libraryWithoutCueFields(_ fields: [String]) throws -> Data {
        var library = try XCTUnwrap(
            JSONSerialization.jsonObject(with: historicalLibrary) as? [[String: Any]]
        )
        var clicks = try XCTUnwrap(library[0]["clicks"] as? [[String: Any]])
        for field in fields { clicks[0].removeValue(forKey: field) }
        library[0]["clicks"] = clicks
        return try JSONSerialization.data(withJSONObject: library, options: [.sortedKeys])
    }

    private func fixture() throws -> (URL, ProjectRepository, StorybirdStoragePreferences) {
        let root = FileManager.default.temporaryDirectory
            .appendingPathComponent("storybird-legacy-contract-\(UUID().uuidString)", isDirectory: true)
            .resolvingSymlinksInPath()
        let repository = ProjectRepository(
            rootURL: root.appendingPathComponent("default", isDirectory: true),
            sharedRootURL: root.appendingPathComponent("shared", isDirectory: true)
        )
        try repository.prepare()
        let domain = "storybird.legacy.contract.\(UUID().uuidString)"
        let defaults = try XCTUnwrap(UserDefaults(suiteName: domain))
        addTeardownBlock {
            try? FileManager.default.removeItem(at: root)
            defaults.removePersistentDomain(forName: domain)
        }
        return (root, repository, StorybirdStoragePreferences(defaults: defaults))
    }

    private func install(
        _ library: Data,
        in repository: ProjectRepository,
        filenames: [String] = ["recording.mp4", "narration.wav", "unreferenced-original.bin"]
    ) throws {
        try repository.prepare()
        let assets = repository.assetsDirectory(projectID: projectID)
        try FileManager.default.createDirectory(at: assets, withIntermediateDirectories: true)
        // These are preservation sentinels, not playable media. These tests stop
        // before rendering and do not claim native media/codec verification.
        for filename in filenames {
            try Data("Synthetic original bytes: \(filename)".utf8)
                .write(to: assets.appendingPathComponent(filename))
        }
        try library.write(to: repository.rootURL.appendingPathComponent("library.json"))
    }

    private func files(in root: URL) throws -> [String: Data] {
        let enumerator = try XCTUnwrap(FileManager.default.enumerator(
            at: root, includingPropertiesForKeys: [.isRegularFileKey]
        ))
        var result: [String: Data] = [:]
        for case let url as URL in enumerator {
            if try url.resourceValues(forKeys: [.isRegularFileKey]).isRegularFile == true {
                result[String(url.path.dropFirst(root.path.count + 1))] = try Data(contentsOf: url)
            }
        }
        return result
    }

    func test_historicalScreenshot_decodePreservesGraphWithoutCreatingVideo() throws {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let project = try XCTUnwrap(decoder.decode(
            [DemoProject].self, from: historicalScreenshotLibrary
        ).first)
        XCTAssertEqual(project.id, projectID)
        XCTAssertEqual(project.revision, 0)
        XCTAssertNil(project.recording)
        XCTAssertTrue(project.clips.isEmpty)
        XCTAssertTrue(project.clicks.isEmpty)
        XCTAssertTrue(project.subtitles.isEmpty)
        XCTAssertTrue(project.effects.isEmpty)
        XCTAssertTrue(project.narrations.isEmpty)
        XCTAssertEqual(project.timelineDuration, 0)
        XCTAssertEqual(project.steps.map(\.assetFilename), ["first.png", "second.png"])
        XCTAssertEqual(project.steps.first?.caption, "Original step caption")
        let hotspot = try XCTUnwrap(project.steps.first?.hotspots.first)
        XCTAssertEqual(hotspot.caption, "Original hotspot caption")
        XCTAssertEqual(hotspot.x, 0.25)
        XCTAssertEqual(hotspot.y, 0.75)
        XCTAssertEqual(hotspot.targetStepID, project.steps.last?.id)
        XCTAssertThrowsError(try VideoProjectValidator.validate(project)) { error in
            XCTAssertEqual(error as? VideoProjectValidationError, .missingRecording)
        }
        XCTAssertThrowsError(try LayeredVideoExporter.validateForExport(project)) { error in
            XCTAssertEqual(error as? VideoProjectValidationError, .missingRecording)
        }
    }

    func test_historicalScreenshot_loadRestartAndFolderSelectionPreserveEveryFile() throws {
        let (root, repository, preferences) = try fixture()
        try install(historicalLibrary, in: repository)
        let screenshots = ProjectRepository(
            rootURL: root.appendingPathComponent("screenshots", isDirectory: true)
        )
        try install(historicalScreenshotLibrary, in: screenshots,
                    filenames: ["first.png", "second.png", "unreferenced-original.bin"])
        let original = try files(in: root)
        let expected = try screenshots.loadProjects()
        XCTAssertEqual(expected.count, 1)
        XCTAssertNil(expected.first?.recording)
        XCTAssertEqual(try screenshots.validatedProjectsForSelection(), expected)
        XCTAssertEqual(try files(in: root), original)
        for _ in 0..<2 {
            // Opening the historical root directly exercises ordinary launch.
            let direct = AppStore(repository: screenshots)
            XCTAssertEqual(direct.projects, expected)
            XCTAssertNil(direct.storageErrorMessage)
            XCTAssertEqual(try files(in: root), original)
        }
        let store = AppStore(repository: repository, storagePreferences: preferences)
        for _ in 0..<2 {
            XCTAssertTrue(store.chooseStorageFolder(screenshots.rootURL))
            XCTAssertEqual(store.projects, expected)
            XCTAssertNil(store.project(id: projectID)?.recording)
            let restarted = AppStore(repository: repository, storagePreferences: preferences)
            XCTAssertEqual(restarted.repository.rootURL, screenshots.rootURL)
            XCTAssertEqual(restarted.projects, expected)
            XCTAssertNil(restarted.storageErrorMessage)
            XCTAssertEqual(try files(in: root), original)
            XCTAssertTrue(store.chooseStorageFolder(nil))
            XCTAssertNotNil(store.project(id: projectID)?.recording)
            XCTAssertEqual(try files(in: root), original)
        }
    }

    func test_historicalScreenshot_hostRejectsTimelineEditsRenderedPreviewAndExport() async throws {
        let (root, repository, preferences) = try fixture()
        try install(historicalScreenshotLibrary, in: repository,
                    filenames: ["first.png", "second.png", "unreferenced-original.bin"])
        let original = try files(in: root)
        let store = AppStore(repository: repository, storagePreferences: preferences)
        let expected = store.projects
        XCTAssertEqual(expected.count, 1)
        let host = StorybirdExternalControlHost(store: store)
        let arguments = try JSONSerialization.data(withJSONObject: [
            "project_id": projectID.uuidString, "expected_revision": 0,
            "time": 0.5, "x": 0.25, "y": 0.75, "text": "Must not be saved",
            "start_time": 0, "end_time": 1, "parent_directory": root.path,
        ])
        // render_preview is the image-producing preview API; preview_project
        // only navigates to the workspace, which displays its unsupported state.
        for name in [
            "storybird_create_click", "storybird_upsert_subtitle",
            "storybird_render_preview", "storybird_export_project",
        ] {
            let response = await host.handle(StorybirdControlRequest(
                name: name, argumentsJSON: arguments
            ))
            XCTAssertTrue(response.isError, "\(name): \(response.text)")
            let expectedError = name == "storybird_create_click"
                ? VideoTimelineEditError.invalidClickPlacement.localizedDescription
                : VideoProjectValidationError.missingRecording.localizedDescription
            XCTAssertTrue(
                response.text.contains(expectedError),
                "\(name) must reject the historical model before media work: \(response.text)"
            )
            XCTAssertEqual(store.projects, expected)
            XCTAssertNil(store.requestedPreviewProjectID)
            XCTAssertFalse(store.isExportActive)
            XCTAssertEqual(try files(in: root), original, name)
        }
        XCTAssertThrowsError(try store.undo(projectID: projectID)) { error in
            XCTAssertEqual(error as? RecordingStoreError, .noUndo)
        }
        XCTAssertEqual(try files(in: root), original)
    }

    func test_historicalScreenshot_headerRenameRejectsWithoutWriting() throws {
        let (root, repository, preferences) = try fixture()
        try install(historicalScreenshotLibrary, in: repository,
                    filenames: ["first.png", "second.png"])
        let store = AppStore(repository: repository, storagePreferences: preferences)
        let project = try XCTUnwrap(store.project(id: projectID))
        let original = try files(in: root)
        var renamed = project
        renamed.name = "Must not rename an unsupported historical project"

        // Exercise the actual header binding without mounting a window.
        ProjectWorkspaceView(store: store, projectID: projectID)
            .projectBinding(for: project).wrappedValue = renamed

        XCTAssertNotNil(store.errorMessage)
        try assertHistoricalEditPreserved(store, project: project, root: root, files: original)
    }

    func test_historicalScreenshot_directGraphEditRejectsWithoutWriting() throws {
        let (root, repository, preferences) = try fixture()
        try install(historicalScreenshotLibrary, in: repository,
                    filenames: ["first.png", "second.png"])
        let store = AppStore(repository: repository, storagePreferences: preferences)
        let project = try XCTUnwrap(store.project(id: projectID))
        let original = try files(in: root)
        var edited = project
        edited.steps[0].caption = "Must not change the historical screenshot"
        edited.steps[0].hotspots[0].caption = "Must not change the historical hotspot"

        XCTAssertThrowsError(try store.saveProject(edited, expectedRevision: project.revision))
        try assertHistoricalEditPreserved(store, project: project, root: root, files: original)
    }

    func test_historicalScreenshot_hostMetadataEditRejectsWithoutWriting() async throws {
        let (root, repository, preferences) = try fixture()
        try install(historicalScreenshotLibrary, in: repository,
                    filenames: ["first.png", "second.png"])
        let store = AppStore(repository: repository, storagePreferences: preferences)
        let project = try XCTUnwrap(store.project(id: projectID))
        let original = try files(in: root)
        let response = await StorybirdExternalControlHost(store: store).handle(
            StorybirdControlRequest(
                name: "storybird_update_project",
                argumentsJSON: try JSONSerialization.data(withJSONObject: [
                    "project_id": projectID.uuidString, "expected_revision": project.revision,
                    "name": "Must not rename historical metadata",
                    "summary": "Must not edit historical metadata",
                ])
            )
        )
        XCTAssertTrue(response.isError, response.text)
        try assertHistoricalEditPreserved(store, project: project, root: root, files: original)
    }

    func test_historicalScreenshot_hostFullReplacementRejectsWithoutWriting() async throws {
        let (root, repository, preferences) = try fixture()
        try install(historicalScreenshotLibrary, in: repository,
                    filenames: ["first.png", "second.png"])
        let store = AppStore(repository: repository, storagePreferences: preferences)
        let project = try XCTUnwrap(store.project(id: projectID))
        let original = try files(in: root)
        var replacement = project
        replacement.name = "Must not replace an unsupported historical project"
        replacement.steps[0].caption = "Must not replace historical screenshot text"
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        let response = await StorybirdExternalControlHost(store: store).handle(
            StorybirdControlRequest(
                name: "storybird_replace_project",
                argumentsJSON: try JSONSerialization.data(withJSONObject: [
                    "project_id": projectID.uuidString, "expected_revision": project.revision,
                    "project_json": String(decoding: try encoder.encode(replacement), as: UTF8.self),
                ])
            )
        )
        XCTAssertTrue(response.isError, response.text)
        try assertHistoricalEditPreserved(store, project: project, root: root, files: original)
    }

    private func assertHistoricalEditPreserved(
        _ store: AppStore, project: DemoProject, root: URL, files original: [String: Data],
        file: StaticString = #filePath, line: UInt = #line
    ) throws {
        // These assertions apply to rejected edits of this unsupported project,
        // not to intentional library writes such as creating a separate project.
        XCTAssertEqual(store.project(id: project.id), project, file: file, line: line)
        XCTAssertEqual(store.project(id: project.id)?.revision, project.revision, file: file, line: line)
        XCTAssertEqual(try files(in: root), original, file: file, line: line)
        XCTAssertThrowsError(try store.undo(projectID: project.id), file: file, line: line) { error in
            XCTAssertEqual(error as? RecordingStoreError, .noUndo, file: file, line: line)
        }
    }

    func test_missingCueComponents_decodeRejectsEachWithoutInventingAGroup() throws {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        // Assert the missing Cue component itself causes rejection, rather than
        // an unrelated date, recording or narration parsing error.
        for field in ["indicator", "description", "cueSubtitle"] {
            XCTAssertThrowsError(try decoder.decode(
                [DemoProject].self, from: libraryWithoutCueFields([field])
            )) { error in
                guard case let DecodingError.keyNotFound(key, context) = error else {
                    return XCTFail("Unexpected decoding error: \(error)")
                }
                XCTAssertEqual(key.stringValue, field)
                XCTAssertTrue(context.codingPath.contains { $0.stringValue == "clicks" })
            }
        }
    }

    func test_missingCueVideo_loadAndRestartPreserveEveryFileAndBlockWrites() throws {
        let (root, repository, preferences) = try fixture()
        try install(try libraryWithoutCueFields(["indicator", "description", "cueSubtitle"]), in: repository)
        let original = try files(in: root)
        XCTAssertThrowsError(try repository.loadProjects())
        XCTAssertEqual(try files(in: root), original)

        for _ in 0..<2 {
            let store = AppStore(repository: repository, storagePreferences: preferences)
            XCTAssertTrue(store.projects.isEmpty)
            XCTAssertNil(store.selectedProjectID)
            XCTAssertNotNil(store.storageErrorMessage)
            XCTAssertEqual(store.repository.rootURL, repository.rootURL)
            XCTAssertThrowsError(try store.repository.saveProjects([]))
            XCTAssertThrowsError(try store.repository.prepareVideoRecordingURL(projectID: projectID))
            XCTAssertEqual(try files(in: root), original)
        }
    }

    func test_missingCueVideo_folderSelectionAndSavedSelectionRestartPreserveBothLibraries() throws {
        let (root, repository, preferences) = try fixture()
        try install(historicalLibrary, in: repository)
        let candidate = ProjectRepository(rootURL: root.appendingPathComponent("unsupported", isDirectory: true))
        try install(try libraryWithoutCueFields(["indicator", "description", "cueSubtitle"]), in: candidate)
        let original = try files(in: root)
        let store = AppStore(repository: repository, storagePreferences: preferences)
        let current = store.projects
        XCTAssertEqual(current.count, 1)
        XCTAssertThrowsError(try candidate.validatedProjectsForSelection())
        for _ in 0..<2 {
            XCTAssertFalse(store.chooseStorageFolder(candidate.rootURL))
            XCTAssertEqual(store.projects, current)
            XCTAssertEqual(store.selectedProjectID, projectID)
            XCTAssertEqual(store.repository.rootURL, repository.rootURL)
            XCTAssertNil(preferences.selectedRootURL)
            XCTAssertNotNil(store.storageErrorMessage)
            XCTAssertEqual(try files(in: root), original)
        }

        preferences.save(candidate.rootURL)
        for _ in 0..<2 {
            let restarted = AppStore(repository: repository, storagePreferences: preferences)
            XCTAssertTrue(restarted.projects.isEmpty)
            XCTAssertNil(restarted.selectedProjectID)
            XCTAssertNotNil(restarted.storageErrorMessage)
            XCTAssertEqual(restarted.repository.rootURL, candidate.rootURL)
            XCTAssertEqual(preferences.selectedRootURL, candidate.rootURL)
            XCTAssertThrowsError(try restarted.repository.saveProjects([]))
            XCTAssertEqual(try files(in: root), original)
        }
        let restarted = AppStore(repository: repository, storagePreferences: preferences)
        XCTAssertTrue(restarted.chooseStorageFolder(nil))
        XCTAssertEqual(restarted.projects, current)
        XCTAssertNil(preferences.selectedRootURL)
        XCTAssertEqual(try files(in: root), original)
    }

    func test_missingCueVideo_mcpCannotReadEditPreviewOrExportUnpublishedProject() async throws {
        let (root, repository, preferences) = try fixture()
        try install(try libraryWithoutCueFields(["indicator", "description", "cueSubtitle"]), in: repository)
        let original = try files(in: root)
        let store = AppStore(repository: repository, storagePreferences: preferences)
        let host = StorybirdExternalControlHost(store: store)
        let arguments = try JSONSerialization.data(withJSONObject: [
            "project_id": projectID.uuidString, "expected_revision": 7, "time": 1,
            "parent_directory": root.path, "name": "Must not be published",
            "click_id": "33333333-3333-3333-3333-333333333333", "caption": "Must not be saved",
        ])
        for name in [
            "storybird_get_project", "storybird_duplicate_project", "storybird_update_click",
            "storybird_preview_project", "storybird_render_preview", "storybird_export_project",
        ] {
            let response = await host.handle(StorybirdControlRequest(
                name: name, argumentsJSON: arguments
            ))
            XCTAssertTrue(response.isError, "\(name): \(response.text)")
            XCTAssertTrue(
                response.text.contains("The project does not exist.")
                    || response.text.contains("The recording project no longer exists."),
                "\(name) must reject the unpublished project before media work: \(response.text)"
            )
            XCTAssertTrue(store.projects.isEmpty)
            XCTAssertNil(store.requestedPreviewProjectID)
            XCTAssertFalse(store.isExportActive)
            XCTAssertEqual(try files(in: root), original, name)
        }
    }

    func test_historicalCueNarration_loadRestartAndFolderSelectionPreservePlaybackContract() throws {
        let (root, repository, preferences) = try fixture()
        let historical = ProjectRepository(rootURL: root.appendingPathComponent("historical", isDirectory: true))
        try install(historicalLibrary, in: historical)
        let original = try files(in: root)
        let decoded = try XCTUnwrap(historical.loadProjects().first)
        XCTAssertNoThrow(try VideoProjectValidator.validate(decoded))
        XCTAssertEqual(decoded.revision, 7)
        XCTAssertTrue(try XCTUnwrap(decoded.clicks.first).isComplete)
        let narration = try XCTUnwrap(decoded.narrations.first)
        XCTAssertEqual(narration.id.uuidString, "44444444-4444-4444-4444-444444444444")
        XCTAssertEqual(narration.voiceProfileID?.uuidString, "55555555-5555-5555-5555-555555555555")
        XCTAssertEqual(narration.filename, "narration.wav")
        XCTAssertEqual(narration.text, "Synthetic narration")
        XCTAssertEqual(narration.language, "english")
        XCTAssertEqual(narration.startTime, 0.5)
        XCTAssertEqual(narration.duration, 1.25)
        XCTAssertEqual(narration.endTime, 1.75)
        XCTAssertEqual(narration.volume, 0.375)
        XCTAssertNil(narration.sceneAnchor)
        XCTAssertEqual(narration.assetID, narration.id)
        XCTAssertEqual(narration.sourceStart, 0)
        XCTAssertEqual(narration.sourceDuration, 1.25)
        XCTAssertFalse(narration.isMuted)
        XCTAssertEqual(narration.fadeIn, 0)
        XCTAssertEqual(narration.fadeOut, 0)
        XCTAssertNil(narration.fadeEnvelope)
        XCTAssertEqual(decoded.sourceAudioVolume, 1)
        XCTAssertFalse(decoded.sourceAudioMuted)

        let store = AppStore(repository: repository, storagePreferences: preferences)
        XCTAssertTrue(store.chooseStorageFolder(historical.rootURL))
        XCTAssertEqual(store.projects, [decoded])
        let restarted = AppStore(repository: repository, storagePreferences: preferences)
        XCTAssertEqual(restarted.projects, [decoded])
        XCTAssertNil(restarted.storageErrorMessage)
        XCTAssertEqual(restarted.selectedStorageRootURL, historical.rootURL)
        XCTAssertTrue(restarted.chooseStorageFolder(nil))
        XCTAssertTrue(restarted.projects.isEmpty)
        XCTAssertTrue(restarted.chooseStorageFolder(historical.rootURL))
        XCTAssertEqual(restarted.projects, [decoded])
        XCTAssertEqual(try files(in: root), original)
    }

    func test_strictProjectEdit_invalidNestedStyleRejectsWholeProjectBeforeClamping() throws {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        decoder.userInfo[.strictProjectEdits] = true
        for component in ["description", "cueSubtitle"] {
            for (field, value) in [("backgroundOpacity", 1.01), ("fontSize", 0.99)] {
                var library = try XCTUnwrap(
                    JSONSerialization.jsonObject(with: historicalLibrary) as? [[String: Any]]
                )
                library[0]["name"] = "Valid edit accompanying invalid style"
                var clicks = try XCTUnwrap(library[0]["clicks"] as? [[String: Any]])
                var cue = try XCTUnwrap(clicks[0][component] as? [String: Any])
                var style = try XCTUnwrap(cue["style"] as? [String: Any])
                style[field] = value
                cue["style"] = style
                clicks[0][component] = cue
                library[0]["clicks"] = clicks
                let data = try JSONSerialization.data(withJSONObject: library[0])
                XCTAssertThrowsError(try decoder.decode(DemoProject.self, from: data)) { error in
                    guard case let DecodingError.dataCorrupted(context) = error else {
                        return XCTFail("Unexpected decoding error: \(error)")
                    }
                    XCTAssertEqual(context.codingPath.map(\.stringValue),
                                   ["clicks", "Index 0", component, "style", field])
                }
            }
        }
    }
}

final class StrictProjectDecodingTests: XCTestCase {
    private func decoder(strict: Bool? = true) -> JSONDecoder {
        let decoder = JSONDecoder()
        if let strict { decoder.userInfo[.strictProjectEdits] = strict }
        decoder.nonConformingFloatDecodingStrategy = .convertFromString(
            positiveInfinity: "Infinity", negativeInfinity: "-Infinity", nan: "NaN"
        )
        return decoder
    }

    func test_strictStyle_invalidRawNumbersRejectBeforeClamping() throws {
        for (key, values) in [
            ("backgroundOpacity", ["-0.001", "1.001", #""Infinity""#, #""-Infinity""#, #""NaN""#]),
            ("fontSize", ["-1", "0", "0.999", #""Infinity""#, #""-Infinity""#, #""NaN""#]),
        ] {
            for value in values {
                let data = Data("{\"\(key)\":\(value)}".utf8)
                XCTAssertThrowsError(try decoder().decode(TextOverlayStyle.self, from: data)) { error in
                    guard case let DecodingError.dataCorrupted(context) = error else {
                        return XCTFail("Unexpected decoding error for \(key)=\(value): \(error)")
                    }
                    XCTAssertEqual(context.codingPath.last?.stringValue, key)
                }
            }
        }
    }

    func test_strictStyle_validBoundsAndAbsentValuesRetainDefaults() throws {
        XCTAssertEqual(try decoder().decode(TextOverlayStyle.self, from: Data("{}".utf8)), .default)
        for (opacity, size) in [(0.0, 1.0), (1.0, 96.0), (0.375, 17.5)] {
            let data = Data("{\"backgroundOpacity\":\(opacity),\"fontSize\":\(size)}".utf8)
            let style = try decoder().decode(TextOverlayStyle.self, from: data)
            XCTAssertEqual(style.backgroundOpacity, opacity)
            XCTAssertEqual(style.fontSize, size)
            XCTAssertEqual(style.backgroundHex, TextOverlayStyle.default.backgroundHex)
            XCTAssertEqual(style.foregroundHex, TextOverlayStyle.default.foregroundHex)
        }
        let onlyOpacity = try decoder().decode(
            TextOverlayStyle.self, from: Data(#"{"backgroundOpacity":0}"#.utf8)
        )
        XCTAssertEqual(onlyOpacity.fontSize, TextOverlayStyle.default.fontSize)
        let onlySize = try decoder().decode(
            TextOverlayStyle.self, from: Data(#"{"fontSize":1}"#.utf8)
        )
        XCTAssertEqual(onlySize.backgroundOpacity, TextOverlayStyle.default.backgroundOpacity)
    }

    func test_nonStrictStyle_absentOrFalseFlagPreservesLibraryClamping() throws {
        for strict: Bool? in [nil, false] {
            let low = try decoder(strict: strict).decode(
                TextOverlayStyle.self, from: Data(#"{"backgroundOpacity":-0.25,"fontSize":-2}"#.utf8)
            )
            XCTAssertEqual(low.backgroundOpacity, 0)
            XCTAssertEqual(low.fontSize, 1)
            let high = try decoder(strict: strict).decode(
                TextOverlayStyle.self, from: Data(#"{"backgroundOpacity":1.25,"fontSize":17}"#.utf8)
            )
            XCTAssertEqual(high.backgroundOpacity, 1)
            XCTAssertEqual(high.fontSize, 17)
        }
    }
}
